[build]
  command = "npm run build"
  publish = "dist"

# Disable secrets scanning for Firebase API key (which is meant to be public)
[build.environment]
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "AIzaSyAZXM4Q-eEcMVIW6e9imI-l4spoDMj7Eog"

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200